---
title: "Electric Vehicles"
summary: The transportation sector is responsible for 26% of U.S. greenhouse gas emissions. Orange County can transition to electric vehicles (EVs) for municipal fleets, garbage trucks and buses.
tags: ["Air and Energy"]
---

 With time, more EVs will become available for more purposes. There are several benefits for Orange County to convert to EVs.

## Reduce Emissions

EVs would help the county meet the emissions goals for their Covenant of Mayors agreement. Even plug in hybrid vehicles greatly reduce CO2 emissions. 

##  Save Money

The considerable up front costs of electric vehicles could be reduced with leasing options. The operating costs of EVs are lower than combustion engine vehicles because there are far fewer maintenance costs, no oil changes, no refrigerants, no transmission fluid. The savings on fuel is dependent on the price of gasoline which is highly variable.

## Clean Air

Combustion engine cars create more air pollution than EVs. Air pollution causes bronchitis, asthma, and emphysema. EVs leave the air cleaner, which would creating a healthier environment for Orange County residents.

## Reduce Noise Pollution

EVs are soundless. Combustion engines are loud. Noise pollution can cause high stress levels, hearing loss and sleep disturbances. An Orange County transition to electric vehicles would mean a healthier life style for its residents.

## Resources


* https://www.fleetcarma.com/government-benefit-electric-vehicle-fleets/
* https://www.tesla.com/support/tesla-leasing
* http://www.sparetheair.com/health.cfm
* https://en.wikipedia.org/wiki/Noise_pollution
